/**
 * Contract ABIs
 *
 * Extracted from compiled Foundry contracts
 */

export const VOID_MARKET_CORE_ABI = [
  {
    type: 'function',
    name: 'createMarket',
    inputs: [
      { name: 'question', type: 'string' },
      { name: 'deadline', type: 'uint256' },
      { name: 'resolutionDeadline', type: 'uint256' },
    ],
    outputs: [{ name: 'marketId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createForkedMarket',
    inputs: [
      { name: 'parentMarketId', type: 'uint256' },
      { name: 'customQuestion', type: 'string' },
      { name: 'deadline', type: 'uint256' },
      { name: 'resolutionDeadline', type: 'uint256' },
    ],
    outputs: [{ name: 'marketId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'placeBet',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'commitmentHash', type: 'bytes32' },
    ],
    outputs: [{ name: 'betId', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'revealBet',
    inputs: [
      { name: 'betId', type: 'uint256' },
      { name: 'direction', type: 'bool' },
      { name: 'salt', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimWinnings',
    inputs: [{ name: 'betId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveMarket',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'outcome', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelMarket',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'marketCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'admin',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'markets',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'question', type: 'string' },
      { name: 'creator', type: 'address' },
      { name: 'deadline', type: 'uint256' },
      { name: 'resolutionDeadline', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'outcome', type: 'bool' },
      { name: 'totalYesAmount', type: 'uint256' },
      { name: 'totalNoAmount', type: 'uint256' },
      { name: 'totalPool', type: 'uint256' },
      { name: 'isForked', type: 'bool' },
      { name: 'parentMarketId', type: 'uint256' },
      { name: 'revealDeadline', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bets',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'bettor', type: 'address' },
      { name: 'marketId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
      { name: 'commitmentHash', type: 'bytes32' },
      { name: 'revealed', type: 'bool' },
      { name: 'direction', type: 'bool' },
      { name: 'timestamp', type: 'uint256' },
      { name: 'claimed', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserBets',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'generateCommitment',
    inputs: [
      { name: 'direction', type: 'bool' },
      { name: 'salt', type: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'pure',
  },
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'question', type: 'string', indexed: false },
      { name: 'deadline', type: 'uint256', indexed: false },
      { name: 'resolutionDeadline', type: 'uint256', indexed: false },
      { name: 'isForked', type: 'bool', indexed: false },
      { name: 'parentMarketId', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetPlaced',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true },
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'commitmentHash', type: 'bytes32', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetRevealed',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true },
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'direction', type: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketResolved',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'outcome', type: 'bool', indexed: false },
      { name: 'totalYesAmount', type: 'uint256', indexed: false },
      { name: 'totalNoAmount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WinningsClaimed',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true },
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'claimer', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const;

export const CLUSTER_MANAGER_ABI = [
  {
    type: 'function',
    name: 'createCluster',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'isPrivate', type: 'bool' },
    ],
    outputs: [{ name: 'clusterId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'inviteToCluster',
    inputs: [
      { name: 'clusterId', type: 'uint256' },
      { name: 'invitee', type: 'address' },
    ],
    outputs: [{ name: 'inviteCode', type: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'joinCluster',
    inputs: [
      { name: 'clusterId', type: 'uint256' },
      { name: 'inviteCode', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'leaveCluster',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferLeadership',
    inputs: [
      { name: 'clusterId', type: 'uint256' },
      { name: 'newLeader', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'clusterCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'clusters',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'name', type: 'string' },
      { name: 'leader', type: 'address' },
      { name: 'energy', type: 'uint256' },
      { name: 'novasWon', type: 'uint256' },
      { name: 'totalNovas', type: 'uint256' },
      { name: 'isPrivate', type: 'bool' },
      { name: 'memberCount', type: 'uint256' },
      { name: 'maxMembers', type: 'uint256' },
      { name: 'createdAt', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'members',
    inputs: [{ name: '', type: 'address' }],
    outputs: [
      { name: 'memberAddress', type: 'address' },
      { name: 'clusterId', type: 'uint256' },
      { name: 'photons', type: 'uint256' },
      { name: 'joinedAt', type: 'uint256' },
      { name: 'isActive', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClusterMembers',
    inputs: [{ name: 'clusterId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isMemberOf',
    inputs: [
      { name: 'memberAddress', type: 'address' },
      { name: 'clusterId', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ClusterCreated',
    inputs: [
      { name: 'clusterId', type: 'uint256', indexed: true },
      { name: 'leader', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'isPrivate', type: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MemberJoined',
    inputs: [
      { name: 'clusterId', type: 'uint256', indexed: true },
      { name: 'member', type: 'address', indexed: true },
      { name: 'inviteCode', type: 'bytes32', indexed: false },
    ],
    anonymous: false,
  },
] as const;

export const NOVA_MANAGER_ABI = [
  {
    type: 'function',
    name: 'startNova',
    inputs: [
      { name: 'cluster1Id', type: 'uint256' },
      { name: 'cluster2Id', type: 'uint256' },
      { name: 'totalRounds', type: 'uint256' },
    ],
    outputs: [{ name: 'novaId', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'createMatch',
    inputs: [
      { name: 'novaId', type: 'uint256' },
      { name: 'star1', type: 'address' },
      { name: 'star2', type: 'address' },
    ],
    outputs: [{ name: 'matchId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveMatch',
    inputs: [
      { name: 'matchId', type: 'uint256' },
      { name: 'outcome', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'advanceRound',
    inputs: [{ name: 'novaId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimReward',
    inputs: [{ name: 'novaId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelNova',
    inputs: [{ name: 'novaId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'novaCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'novas',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'cluster1Id', type: 'uint256' },
      { name: 'cluster2Id', type: 'uint256' },
      { name: 'totalRounds', type: 'uint256' },
      { name: 'currentRound', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'prizePool', type: 'uint256' },
      { name: 'winningClusterId', type: 'uint256' },
      { name: 'cluster1TotalPhotons', type: 'uint256' },
      { name: 'cluster2TotalPhotons', type: 'uint256' },
      { name: 'startedAt', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'matches',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'novaId', type: 'uint256' },
      { name: 'round', type: 'uint256' },
      { name: 'star1', type: 'address' },
      { name: 'star2', type: 'address' },
      { name: 'marketId', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'winner', type: 'address' },
      { name: 'star1Photons', type: 'uint256' },
      { name: 'star2Photons', type: 'uint256' },
      { name: 'bettingDeadline', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNovaMatches',
    inputs: [{ name: 'novaId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'NovaCreated',
    inputs: [
      { name: 'novaId', type: 'uint256', indexed: true },
      { name: 'cluster1Id', type: 'uint256', indexed: true },
      { name: 'cluster2Id', type: 'uint256', indexed: true },
      { name: 'totalRounds', type: 'uint256', indexed: false },
      { name: 'prizePool', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MatchCreated',
    inputs: [
      { name: 'matchId', type: 'uint256', indexed: true },
      { name: 'novaId', type: 'uint256', indexed: true },
      { name: 'round', type: 'uint256', indexed: false },
      { name: 'star1', type: 'address', indexed: false },
      { name: 'star2', type: 'address', indexed: false },
      { name: 'marketId', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MatchResolved',
    inputs: [
      { name: 'matchId', type: 'uint256', indexed: true },
      { name: 'novaId', type: 'uint256', indexed: true },
      { name: 'winner', type: 'address', indexed: false },
      { name: 'star1Photons', type: 'uint256', indexed: false },
      { name: 'star2Photons', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const;
