import { Market, Bet, Transaction, Star, Cluster, Nova, ChainBalance } from "@/types"

// Helper to create future dates
const daysFromNow = (days: number) => new Date(Date.now() + days * 24 * 60 * 60 * 1000)
const hoursFromNow = (hours: number) => new Date(Date.now() + hours * 60 * 60 * 1000)

export const mockMarkets: Market[] = [
  {
    id: "1",
    title: "WILL ETH HIT $5K BY Q1 2025?",
    description: "Ethereum price reaches $5,000 USD before January 31, 2025",
    category: "crypto",
    creatorAddress: "0x7a3b...f92d",
    creatorName: "PROPHET.VOID",
    endDate: daysFromNow(45),
    totalBets: 847,
    totalPool: 12.5,
    resolutionCriteria: "Ethereum spot price on CoinGecko exceeds $5,000 USD at any point before January 31, 2025 23:59 UTC",
    oracleType: "stork",
    oracleSource: "stork.api/eth-usd",
    status: "active",
    createdAt: new Date("2024-11-01"),
  },
  {
    id: "2",
    title: "TRUMP WINS 2024 PRESIDENTIAL ELECTION?",
    description: "Donald Trump wins the 2024 US Presidential Election",
    category: "politics",
    creatorAddress: "0x3c4d...a82b",
    creatorName: "DEGEN.ORACLE",
    endDate: daysFromNow(5),
    totalBets: 2147,
    totalPool: 156.7,
    resolutionCriteria: "Official AP call of the 2024 US Presidential Election winner",
    oracleType: "manual",
    status: "active",
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "3",
    title: "CHIEFS WIN SUPER BOWL 2025?",
    description: "Kansas City Chiefs win Super Bowl LIX",
    category: "sports",
    creatorAddress: "0x9f2e...c73a",
    creatorName: "SPORTS.VOID",
    endDate: hoursFromNow(12),
    totalBets: 534,
    totalPool: 28.3,
    resolutionCriteria: "Official NFL announcement of Super Bowl LIX winner",
    oracleType: "manual",
    status: "active",
    createdAt: new Date("2024-10-15"),
  },
  {
    id: "4",
    title: "BTC BREAKS $100K IN 2024?",
    description: "Bitcoin reaches $100,000 USD before end of 2024",
    category: "crypto",
    creatorAddress: "0x7a3b...f92d",
    creatorName: "PROPHET.VOID",
    endDate: daysFromNow(30),
    totalBets: 1823,
    totalPool: 89.2,
    outcome: "YES",
    resolutionCriteria: "Bitcoin spot price on CoinGecko exceeds $100,000 USD",
    oracleType: "stork",
    status: "resolved",
    resolutionDate: new Date("2024-11-20"),
    createdAt: new Date("2024-09-01"),
  },
  {
    id: "5",
    title: "SOLANA FLIPS ETHEREUM IN TVL?",
    description: "Solana total value locked exceeds Ethereum",
    category: "crypto",
    creatorAddress: "0x5d1f...b92c",
    creatorName: "DEFI.WHALE",
    endDate: daysFromNow(60),
    totalBets: 412,
    totalPool: 18.7,
    resolutionCriteria: "DefiLlama shows Solana TVL > Ethereum TVL",
    oracleType: "stork",
    status: "active",
    createdAt: new Date("2024-11-05"),
  },
  {
    id: "6",
    title: "TAYLOR SWIFT ENDORSES CANDIDATE?",
    description: "Taylor Swift publicly endorses a 2024 presidential candidate",
    category: "culture",
    creatorAddress: "0x2e8c...d41a",
    creatorName: "POP.ORACLE",
    endDate: daysFromNow(3),
    totalBets: 892,
    totalPool: 34.1,
    resolutionCriteria: "Official public endorsement from Taylor Swift social media or statement",
    oracleType: "manual",
    status: "active",
    createdAt: new Date("2024-10-20"),
  },
]

export const mockUserBets: Bet[] = [
  {
    id: "bet-1",
    marketId: "1",
    marketTitle: "WILL ETH HIT $5K BY Q1 2025?",
    userAddress: "0xuser...1234",
    outcome: "YES",
    amount: 0.5,
    status: "in_void",
    placedAt: new Date("2024-10-15"),
    commitmentHash: "0xabc123...",
  },
  {
    id: "bet-2",
    marketId: "4",
    marketTitle: "BTC BREAKS $100K IN 2024?",
    userAddress: "0xuser...1234",
    outcome: "YES",
    amount: 1.0,
    status: "claimable",
    payout: 2.3,
    placedAt: new Date("2024-09-15"),
    commitmentHash: "0xdef456...",
  },
  {
    id: "bet-3",
    marketId: "2",
    marketTitle: "TRUMP WINS 2024 PRESIDENTIAL ELECTION?",
    userAddress: "0xuser...1234",
    outcome: "NO",
    amount: 0.25,
    status: "in_void",
    placedAt: new Date("2024-10-25"),
    commitmentHash: "0xghi789...",
  },
  {
    id: "bet-4",
    marketId: "old-market",
    marketTitle: "DOGE TO $1 BY CHRISTMAS?",
    userAddress: "0xuser...1234",
    outcome: "YES",
    amount: 0.25,
    status: "lost",
    placedAt: new Date("2024-08-01"),
    commitmentHash: "0xjkl012...",
  },
  {
    id: "bet-5",
    marketId: "old-market-2",
    marketTitle: "SOL HITS $200 BY EOY?",
    userAddress: "0xuser...1234",
    outcome: "YES",
    amount: 0.5,
    status: "won",
    payout: 0.8,
    placedAt: new Date("2024-07-15"),
    claimedAt: new Date("2024-10-20"),
    commitmentHash: "0xmno345...",
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "tx-1",
    type: "deposit",
    amount: 1.0,
    status: "confirmed",
    timestamp: new Date("2024-10-15"),
    txHash: "0x123...",
  },
  {
    id: "tx-2",
    type: "bet",
    amount: -0.5,
    status: "confirmed",
    timestamp: new Date("2024-10-15"),
    marketTitle: "ETH $5K...",
  },
  {
    id: "tx-3",
    type: "winnings",
    amount: 2.3,
    status: "confirmed",
    timestamp: new Date("2024-11-20"),
    marketTitle: "BTC $100K...",
  },
  {
    id: "tx-4",
    type: "withdraw",
    amount: -0.5,
    status: "confirmed",
    timestamp: new Date("2024-10-10"),
    txHash: "0x456...",
  },
]

export const mockUserBalance = 245.50
export const mockUserAddress = "0x7A3B...F92D"

// Current user's star profile
export const mockStar: Star = {
  id: "star-1",
  address: "0x7A3B...F92D",
  name: "COSMIC VOYAGER",
  starType: "blue-supergiant",
  bio: "Traversing the void since 2024",
  telegramId: "@cosmicvoyager",
  clusterId: "cluster-1",
  totalPhotons: 1250,
  createdAt: new Date("2024-10-01"),
}

// Chain balances for unified display
export const mockChainBalances: ChainBalance[] = [
  { chainId: 1, chainName: "Ethereum", balance: 100.00, symbol: "USDC" },
  { chainId: 42161, chainName: "Arbitrum", balance: 85.50, symbol: "USDC" },
  { chainId: 8453, chainName: "Base", balance: 60.00, symbol: "USDC" },
]

// Mock clusters
export const mockClusters: Cluster[] = [
  {
    id: "cluster-1",
    name: "VOID SEEKERS",
    description: "We seek truth in the darkness",
    leaderId: "star-1",
    members: [
      {
        odId: "star-1",
        name: "COSMIC VOYAGER",
        starType: "blue-supergiant",
        photons: 450,
        novasPlayed: 12,
        novasWon: 8,
        joinedAt: new Date("2024-10-01"),
      },
      {
        odId: "star-2",
        name: "NOVA HUNTER",
        starType: "red-giant",
        photons: 380,
        novasPlayed: 10,
        novasWon: 6,
        joinedAt: new Date("2024-10-05"),
      },
      {
        odId: "star-3",
        name: "STELLAR DRIFT",
        starType: "neutron",
        photons: 290,
        novasPlayed: 8,
        novasWon: 5,
        joinedAt: new Date("2024-10-10"),
      },
      {
        odId: "star-4",
        name: "DARK MATTER",
        starType: "white-dwarf",
        photons: 130,
        novasPlayed: 5,
        novasWon: 2,
        joinedAt: new Date("2024-10-15"),
      },
    ],
    energy: 3450,
    totalNovas: 15,
    novasWon: 10,
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "cluster-2",
    name: "COSMIC RAIDERS",
    description: "Raiding markets across the galaxy",
    leaderId: "star-5",
    members: [
      {
        odId: "star-5",
        name: "GALACTIC KING",
        starType: "yellow-sun",
        photons: 520,
        novasPlayed: 14,
        novasWon: 9,
        joinedAt: new Date("2024-09-15"),
      },
      {
        odId: "star-6",
        name: "NEBULA QUEEN",
        starType: "binary",
        photons: 410,
        novasPlayed: 11,
        novasWon: 7,
        joinedAt: new Date("2024-09-20"),
      },
      {
        odId: "star-7",
        name: "PHOTON SLAYER",
        starType: "blue-supergiant",
        photons: 350,
        novasPlayed: 9,
        novasWon: 5,
        joinedAt: new Date("2024-09-25"),
      },
    ],
    energy: 4200,
    totalNovas: 18,
    novasWon: 12,
    createdAt: new Date("2024-09-15"),
  },
  {
    id: "cluster-3",
    name: "DARK PROPHETS",
    description: "We predict the unpredictable",
    leaderId: "star-8",
    members: [
      {
        odId: "star-8",
        name: "ORACLE PRIME",
        starType: "neutron",
        photons: 680,
        novasPlayed: 20,
        novasWon: 14,
        joinedAt: new Date("2024-08-01"),
      },
      {
        odId: "star-9",
        name: "VOID SEER",
        starType: "white-dwarf",
        photons: 540,
        novasPlayed: 16,
        novasWon: 10,
        joinedAt: new Date("2024-08-10"),
      },
    ],
    energy: 5800,
    totalNovas: 25,
    novasWon: 18,
    createdAt: new Date("2024-08-01"),
  },
]

// Mock nova (active)
export const mockNova: Nova = {
  id: "nova-1",
  cluster1Id: "cluster-1",
  cluster2Id: "cluster-2",
  cluster1Name: "VOID SEEKERS",
  cluster2Name: "COSMIC RAIDERS",
  status: "active",
  wagerAmount: 50,
  matches: [
    {
      id: "match-1",
      novaId: "nova-1",
      star1Id: "star-1",
      star2Id: "star-5",
      star1Name: "COSMIC VOYAGER",
      star2Name: "GALACTIC KING",
      marketId: "1",
      marketTitle: "WILL ETH HIT $5K BY Q1 2025?",
      star1Bet: { outcome: "YES", amount: 10 },
      star2Bet: { outcome: "NO", amount: 10 },
      photonsAwarded: 100,
      status: "active",
    },
    {
      id: "match-2",
      novaId: "nova-1",
      star1Id: "star-2",
      star2Id: "star-6",
      star1Name: "NOVA HUNTER",
      star2Name: "NEBULA QUEEN",
      marketId: "2",
      marketTitle: "TRUMP WINS 2024 PRESIDENTIAL ELECTION?",
      star1Bet: { outcome: "YES", amount: 10 },
      photonsAwarded: 100,
      status: "active",
    },
    {
      id: "match-3",
      novaId: "nova-1",
      star1Id: "star-3",
      star2Id: "star-7",
      star1Name: "STELLAR DRIFT",
      star2Name: "PHOTON SLAYER",
      marketId: "3",
      marketTitle: "CHIEFS WIN SUPER BOWL 2025?",
      photonsAwarded: 100,
      status: "pending",
    },
  ],
  startedAt: new Date("2024-11-01"),
}

// Top clusters for leaderboard
export const mockTopClusters = mockClusters
  .sort((a, b) => b.energy - a.energy)
  .slice(0, 5)
